#!/usr/bin/env python
"""
LLM答案评估器

功能特点：
1. 使用LLM评估RAG系统的答案质量
2. 多维度评估指标：准确性、相关性、完整性、忠实性等
3. 结构化的评估结果输出
4. 批量评估功能
"""

import os
import json
import asyncio
import logging
import time
from pathlib import Path
from typing import List, Dict, Any, Optional
import pandas as pd
from datetime import datetime

# Add project root directory to Python path
import sys
sys.path.append(str(Path(__file__).parent.parent))

from lightrag.llm.openai import openai_complete_if_cache
from dotenv import load_dotenv

load_dotenv(dotenv_path=".env", override=False)

class LLMAnswerEvaluator:
    def __init__(self, config):
        self.config = config
        self.evaluation_results = []
        self.existing_evaluations = {}  # 存储已有评估结果的索引，用于快速查找
        self.setup_logging()
        self.load_existing_evaluations()  # 加载已有评估结果
        
    def setup_logging(self):
        """配置日志"""
        log_file = os.path.join(self.config.output_dir, "llm_evaluation.log")
        os.makedirs(self.config.output_dir, exist_ok=True)
        
        # 根据 quiet 配置决定是否输出到控制台
        handlers = [logging.FileHandler(log_file, encoding='utf-8')]
        if not getattr(self.config, 'quiet', False):
            handlers.append(logging.StreamHandler(sys.stdout))
        
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(levelname)s - %(message)s',
            handlers=handlers,
            force=True  # 强制重新配置
        )
        self.logger = logging.getLogger('llm_evaluator')
        
        # 静默模式下设置更高的日志级别
        if getattr(self.config, 'quiet', False):
            self.logger.setLevel(logging.WARNING)

    def get_accuracy_evaluation_prompt(self, question: str, expected_answer: str, 
                                     generated_answer: str, evidence_pages: str = "", 
                                     evidence_sources: str = "") -> str:
        """生成准确性评估的prompt"""
        prompt = f"""You are an expert evaluator tasked with assessing the accuracy of answers generated by a RAG (Retrieval-Augmented Generation) system.

**Task**: Evaluate whether the generated answer correctly responds to the given question based on the expected answer.

**Question**: {question}

**Expected Answer**: {expected_answer}

**Generated Answer**: {generated_answer}

**Evidence Pages**: {evidence_pages}

**Evidence Sources**: {evidence_sources}

**Evaluation Criteria**:
1. **Accuracy (0 or 1)**: Does the generated answer match the factual content of the expected answer?
   - 1: The generated answer is factually correct and aligns with the expected answer
   - 0: The generated answer is factually incorrect or contradicts the expected answer

**Instructions**:
- Focus on factual correctness, not writing style or format
- Consider partial matches: if the generated answer contains the correct information but includes additional context, it should still be considered accurate
- For numerical answers, check if the values match or are equivalent
- For list answers, check if all key elements are present
- If the expected answer is "Not answerable" and the generated answer indicates inability to answer, consider it accurate

**Output Format**:
Please respond with a JSON object containing only:
{{
    "accuracy": 0 or 1,
    "reasoning": "Brief explanation of your evaluation"
}}
"""
        return prompt

    def get_comprehensive_evaluation_prompt(self, question: str, expected_answer: str,
                                          generated_answer: str, evidence_pages: str = "",
                                          evidence_sources: str = "") -> str:
        """生成综合评估的prompt"""
        prompt = f"""You are an expert evaluator assessing the quality of answers generated by a RAG system across multiple dimensions.

**Question**: {question}

**Expected Answer**: {expected_answer}

**Generated Answer**: {generated_answer}

**Evidence Pages**: {evidence_pages}

**Evidence Sources**: {evidence_sources}

**Evaluation Dimensions** (Rate each from 0 to 1):

1. **Accuracy (0 or 1)**: Factual correctness compared to expected answer
   - 1: Factually correct and aligns with expected answer
   - 0: Factually incorrect or contradicts expected answer

2. **Relevance (0 to 1)**: How well the answer addresses the question
   - 1.0: Directly and completely addresses the question
   - 0.5: Partially addresses the question
   - 0.0: Does not address the question

3. **Completeness (0 to 1)**: How comprehensive the answer is
   - 1.0: Provides complete information as expected
   - 0.5: Provides partial but useful information
   - 0.0: Incomplete or missing key information

4. **Faithfulness (0 to 1)**: Whether the answer is grounded in evidence
   - 1.0: Answer is fully supported by evidence
   - 0.5: Answer is partially supported by evidence
   - 0.0: Answer contains unsupported claims

5. **Clarity (0 to 1)**: How clear and understandable the answer is
   - 1.0: Very clear and well-structured
   - 0.5: Reasonably clear with minor issues
   - 0.0: Unclear or confusing

6. **Consistency (0 to 1)**: Internal consistency of the answer
   - 1.0: Completely consistent, no contradictions
   - 0.5: Mostly consistent with minor issues
   - 0.0: Contains contradictions or inconsistencies

**Special Cases**:
- If expected answer is "Not answerable" and generated answer appropriately indicates inability to answer, rate accuracy as 1
- Consider format requirements (e.g., if expected format is "List" but answer is string, note in reasoning)

**Output Format**:
Respond with a JSON object:
{{
    "accuracy": 0 or 1,
    "relevance": 0.0 to 1.0,
    "completeness": 0.0 to 1.0,
    "faithfulness": 0.0 to 1.0,
    "clarity": 0.0 to 1.0,
    "consistency": 0.0 to 1.0,
    "overall_score": 0.0 to 1.0,
    "reasoning": "Brief explanation of your evaluation for each dimension"
}}
"""
        return prompt

    def fix_json_format(self, json_content: str) -> str:
        """修复常见的JSON格式问题"""
        import re
        
        try:
            # 移除可能的Markdown代码块标记
            json_content = re.sub(r'```json\s*\n?', '', json_content)
            json_content = re.sub(r'\n?```', '', json_content)
            json_content = json_content.strip()
            
            # 处理重复的reasoning字段问题 - 使用更简单的方法
            # 找到所有reasoning字段的起始位置
            reasoning_pattern = r'"reasoning":\s*"'
            matches = list(re.finditer(reasoning_pattern, json_content))
            
            if len(matches) > 1:
                # 如果有多个reasoning字段，保留第一个完整的
                first_match_start = matches[0].start()
                
                # 找到第一个reasoning字段的结束位置
                quote_start = matches[0].end() - 1  # 指向开始的引号
                quote_count = 0
                end_pos = quote_start
                
                for i, char in enumerate(json_content[quote_start:], quote_start):
                    if char == '"' and (i == quote_start or json_content[i-1] != '\\'):
                        quote_count += 1
                        if quote_count == 2:  # 找到结束引号
                            end_pos = i + 1
                            break
                
                # 保留第一个reasoning字段，移除后续的
                before_first = json_content[:first_match_start]
                first_reasoning = json_content[first_match_start:end_pos]
                
                # 找到第一个reasoning字段后的下一个字段或结束
                after_first = json_content[end_pos:]
                # 移除后续的reasoning字段
                after_first = re.sub(r',?\s*"reasoning":\s*"[^"]*(?:\\"[^"]*)*"', '', after_first)
                
                json_content = before_first + first_reasoning + after_first
            
            # 确保JSON对象正确闭合
            if json_content and not json_content.endswith('}'):
                # 计算大括号平衡
                open_braces = json_content.count('{')
                close_braces = json_content.count('}')
                if open_braces > close_braces:
                    # 先确保最后一个字段正确结束
                    if not json_content.rstrip().endswith(('"', '}', ']')):
                        # 可能有截断的字符串，尝试闭合
                        if '"' in json_content and json_content.count('"') % 2 == 1:
                            json_content = json_content.rstrip() + '"'
                    # 添加缺失的大括号
                    json_content += '}' * (open_braces - close_braces)
            
            # 移除控制字符
            json_content = re.sub(r'[\x00-\x1f\x7f-\x9f]', '', json_content)
            
            return json_content.strip()
            
        except Exception as e:
            self.logger.warning(f"修复JSON格式时出错: {e}")
            return json_content
    
    def create_fallback_evaluation(self, response: str) -> Dict[str, Any]:
        """当JSON解析失败时创建基本的评估结果"""
        import re
        
        # 尝试从响应中提取关键信息
        fallback_result = {
            "accuracy": None,
            "relevance": None,
            "completeness": None,
            "faithfulness": None,
            "clarity": None,
            "consistency": None,
            "overall_score": None,
            "reasoning": "JSON解析失败，无法获取详细评估"
        }
        
        # 尝试提取准确性值
        accuracy_patterns = [
            r'"accuracy":\s*(\d+)',
            r'accuracy.*?(\d+)',
            r'准确.*?(\d+)',
            r'correct.*?(\d+)',
            r'accurate.*?(\d+)'
        ]
        
        for pattern in accuracy_patterns:
            match = re.search(pattern, response, re.IGNORECASE)
            if match:
                try:
                    accuracy_value = int(match.group(1))
                    if accuracy_value in [0, 1]:
                        fallback_result["accuracy"] = accuracy_value
                        break
                except ValueError:
                    continue
        
        # 如果找不到准确性值，尝试根据关键词判断
        if fallback_result["accuracy"] is None:
            positive_keywords = ["correct", "accurate", "right", "yes", "true", "match"]
            negative_keywords = ["incorrect", "wrong", "false", "no", "mismatch", "contradiction"]
            
            response_lower = response.lower()
            if any(keyword in response_lower for keyword in positive_keywords):
                fallback_result["accuracy"] = 1
            elif any(keyword in response_lower for keyword in negative_keywords):
                fallback_result["accuracy"] = 0
        
        # 设置默认值（如果仍然为None）
        if fallback_result["accuracy"] is None:
            fallback_result["accuracy"] = 0  # 保守估计
        
        # 对于综合评估，尝试提取其他指标
        if "relevance" in response.lower():
            relevance_match = re.search(r'"relevance":\s*([\d.]+)', response, re.IGNORECASE)
            if relevance_match:
                try:
                    fallback_result["relevance"] = float(relevance_match.group(1))
                except ValueError:
                    pass
        
        self.logger.info(f"创建fallback评估结果: accuracy={fallback_result['accuracy']}")
        return fallback_result

    async def evaluate_single_answer(self, question: str, expected_answer: str,
                                   generated_answer: str, evidence_pages: str = "",
                                   evidence_sources: str = "", doc_id: str = "",
                                   evaluation_type: str = "comprehensive") -> Dict[str, Any]:
        """评估单个答案"""
        start_time = time.time()
        
        try:
            if evaluation_type == "accuracy_only":
                prompt = self.get_accuracy_evaluation_prompt(
                    question, expected_answer, generated_answer, evidence_pages, evidence_sources
                )
            else:
                prompt = self.get_comprehensive_evaluation_prompt(
                    question, expected_answer, generated_answer, evidence_pages, evidence_sources
                )
            
            self.logger.info(f"开始评估答案 (类型: {evaluation_type})")
            self.logger.info(f"问题: {question[:100]}...")
            
            # 调用LLM进行评估
            eval_model = getattr(self.config, 'model', 'gpt-4o')  # 使用配置中的模型
            response = await openai_complete_if_cache(
                model=eval_model,
                prompt=prompt,
                system_prompt="You are an expert evaluator. Provide accurate and fair evaluations based on the given criteria.",
                api_key=self.config.api_key,
                base_url=self.config.base_url,
                temperature=0.1,  # 低温度确保评估一致性
                max_tokens=1000
            )
            
            evaluation_time = time.time() - start_time
            
            # 解析JSON响应
            try:
                evaluation_result = json.loads(response)
            except json.JSONDecodeError:
                import re
                
                # 首先尝试提取被```json```包围的内容
                json_code_block_match = re.search(r'```json\s*\n(.*?)\n```', response, re.DOTALL)
                if json_code_block_match:
                    json_content = json_code_block_match.group(1).strip()
                    try:
                        evaluation_result = json.loads(json_content)
                    except json.JSONDecodeError as e:
                        self.logger.warning(f"代码块中的JSON解析失败: {e}")
                        # 尝试修复常见的JSON格式问题（如重复的reasoning字段）
                        json_content = self.fix_json_format(json_content)
                        try:
                            evaluation_result = json.loads(json_content)
                        except json.JSONDecodeError:
                            # 最后的fallback：创建基本的评估结果
                            self.logger.warning("JSON修复失败，使用默认评估结果")
                            evaluation_result = self.create_fallback_evaluation(response)
                else:
                    # 尝试提取任何JSON对象
                    json_match = re.search(r'\{.*\}', response, re.DOTALL)
                    if json_match:
                        json_content = json_match.group().strip()
                        try:
                            evaluation_result = json.loads(json_content)
                        except json.JSONDecodeError:
                            json_content = self.fix_json_format(json_content)
                            try:
                                evaluation_result = json.loads(json_content)
                            except json.JSONDecodeError:
                                # 最后的fallback：创建基本的评估结果
                                self.logger.warning("JSON修复失败，使用默认评估结果")
                                evaluation_result = self.create_fallback_evaluation(response)
                    else:
                        raise ValueError("无法从响应中提取有效的JSON")
            
            # 添加元数据
            evaluation_result.update({
                "doc_id": doc_id,
                "question": question,
                "expected_answer": expected_answer,
                "generated_answer": generated_answer,
                "evidence_pages": evidence_pages,
                "evidence_sources": evidence_sources,
                "evaluation_type": evaluation_type,
                "evaluation_time": evaluation_time,
                "timestamp": datetime.now().isoformat(),
                "success": True,
                "error": None
            })
            
            self.logger.info(f"评估完成，耗时: {evaluation_time:.2f}秒")
            return evaluation_result
            
        except Exception as e:
            evaluation_time = time.time() - start_time
            error_msg = f"评估过程中出错: {str(e)}"
            self.logger.error(error_msg)
            
            return {
                "doc_id": doc_id,
                "question": question,
                "expected_answer": expected_answer,
                "generated_answer": generated_answer,
                "evidence_pages": evidence_pages,
                "evidence_sources": evidence_sources,
                "evaluation_type": evaluation_type,
                "evaluation_time": evaluation_time,
                "timestamp": datetime.now().isoformat(),
                "success": False,
                "error": error_msg,
                "accuracy": None,
                "reasoning": None
            }

    async def evaluate_rag_results(self, results_file: str, evaluation_type: str = "comprehensive",
                                 max_evaluations: int = None) -> None:
        """评估RAG结果文件"""
        self.logger.info(f"开始评估RAG结果文件: {results_file}")
        
        # 加载RAG评估结果
        with open(results_file, 'r', encoding='utf-8') as f:
            rag_results = json.load(f)
        
        if max_evaluations:
            rag_results = rag_results[:max_evaluations]
            self.logger.info(f"限制评估数量为: {max_evaluations}")
        
        total_items = len(rag_results)
        self.logger.info(f"开始评估 {total_items} 个结果")
        
        # 检测结果类型
        if rag_results and "vlm_result" in rag_results[0]:
            self.logger.info("检测到VLM结果格式")
            await self.evaluate_vlm_results(rag_results, evaluation_type)
        else:
            self.logger.info("检测到RAG结果格式")
            await self.evaluate_standard_rag_results(rag_results, evaluation_type)

    async def evaluate_multiple_results(self, results_files: List[str], evaluation_type: str = "comprehensive",
                                      max_evaluations: int = None) -> None:
        """评估多个结果文件（RAG和VLM）"""
        self.logger.info(f"开始评估多个结果文件: {results_files}")
        
        start_time = time.time()
        all_results_by_type = {}
        
        # 按文件类型分别加载结果
        for results_file in results_files:
            self.logger.info(f"加载结果文件: {results_file}")
            
            with open(results_file, 'r', encoding='utf-8') as f:
                results = json.load(f)
            
            # 检测文件类型并标记
            if results and "vlm_result" in results[0]:
                file_type = "vlm"
                self.logger.info(f"检测到VLM结果格式: {len(results)} 个结果")
            else:
                file_type = "rag"
                self.logger.info(f"检测到RAG结果格式: {len(results)} 个结果")
            
            # 为每个结果添加文件类型标记
            for result in results:
                result["_file_type"] = file_type
                result["_source_file"] = results_file
            
            all_results_by_type[file_type] = {
                "results": results,
                "source_file": results_file
            }
        
        # 如果有限制，按问题数量限制而不是结果数量
        if max_evaluations:
            for file_type in all_results_by_type:
                original_count = len(all_results_by_type[file_type]["results"])
                all_results_by_type[file_type]["results"] = all_results_by_type[file_type]["results"][:max_evaluations]
                limited_count = len(all_results_by_type[file_type]["results"])
                self.logger.info(f"限制{file_type}结果数量: {original_count} -> {limited_count}")
        
        # 合并所有结果进行评估
        all_results = []
        for file_type, data in all_results_by_type.items():
            all_results.extend(data["results"])
        
        total_items = len(all_results)
        skipped_count = 0
        completed_count = 0
        new_evaluations = []
        
        # 统计已有评估
        if self.existing_evaluations:
            existing_count = len(self.existing_evaluations)
            self.logger.info(f"发现 {existing_count} 个已有的LLM评估结果，将跳过重复评估")
        
        self.logger.info(f"开始评估总计 {total_items} 个结果")
        
        # 评估所有结果
        for i, result in enumerate(all_results, 1):
            self.logger.info(f"\n📋 [{i}/{total_items}] 评估{result['_file_type'].upper()}结果")
            
            # 检查是否有任何类型的error，如果有则跳过
            if self.has_any_error(result):
                skipped_count += 1
                self.logger.info(f"  ⏭️ 跳过有错误的查询: {self.get_error_summary(result)}")
                continue
            
            if result["_file_type"] == "vlm":
                # 评估VLM结果
                if result.get("vlm_result") and result["vlm_result"].get("success"):
                    method = "vlm"
                    
                    # 检查是否已完成评估
                    if self.is_evaluation_completed(result["doc_id"], result["question"], method):
                        completed_count += 1
                        self.logger.info(f"  ✅ 跳过已完成的{method}评估")
                        # 将已有结果添加到当前批次
                        existing_eval = self.get_existing_evaluation(result["doc_id"], result["question"], method)
                        if existing_eval:
                            existing_eval["source_file"] = result["_source_file"]  # 更新源文件信息
                            new_evaluations.append(existing_eval)
                        continue
                    
                    eval_result = await self.evaluate_single_answer(
                        question=result["question"],
                        expected_answer=str(result["expected_answer"]),
                        generated_answer=str(result["vlm_result"]["result"]),
                        evidence_pages=result.get("evidence_pages", ""),
                        evidence_sources=result.get("evidence_sources", ""),
                        doc_id=result["doc_id"],
                        evaluation_type=evaluation_type
                    )
                    eval_result["method"] = method
                    eval_result["model"] = result["vlm_result"].get("model", "unknown")
                    eval_result["source_file"] = result["_source_file"]
                    
                    new_evaluations.append(eval_result)
                    
                    # 更新索引
                    key = (result["doc_id"], result["question"], method)
                    self.existing_evaluations[key] = eval_result
                    
            else:  # RAG结果
                # 评估hybrid结果
                if result.get("hybrid_result") and result["hybrid_result"].get("success"):
                    method = "hybrid"
                    
                    # 检查是否已完成评估
                    if self.is_evaluation_completed(result["doc_id"], result["question"], method):
                        completed_count += 1
                        self.logger.info(f"  ✅ 跳过已完成的{method}评估")
                        # 将已有结果添加到当前批次
                        existing_eval = self.get_existing_evaluation(result["doc_id"], result["question"], method)
                        if existing_eval:
                            existing_eval["source_file"] = result["_source_file"]
                            new_evaluations.append(existing_eval)
                    else:
                        hybrid_eval = await self.evaluate_single_answer(
                            question=result["question"],
                            expected_answer=str(result["expected_answer"]),
                            generated_answer=str(result["hybrid_result"]["result"]),
                            evidence_pages=result.get("evidence_pages", ""),
                            evidence_sources=result.get("evidence_sources", ""),
                            doc_id=result["doc_id"],
                            evaluation_type=evaluation_type
                        )
                        hybrid_eval["method"] = method
                        hybrid_eval["source_file"] = result["_source_file"]
                        
                        new_evaluations.append(hybrid_eval)
                        
                        # 更新索引
                        key = (result["doc_id"], result["question"], method)
                        self.existing_evaluations[key] = hybrid_eval
                
                # 评估mix结果
                if result.get("mix_result") and result["mix_result"].get("success"):
                    method = "mix"
                    
                    # 检查是否已完成评估
                    if self.is_evaluation_completed(result["doc_id"], result["question"], method):
                        completed_count += 1
                        self.logger.info(f"  ✅ 跳过已完成的{method}评估")
                        # 将已有结果添加到当前批次
                        existing_eval = self.get_existing_evaluation(result["doc_id"], result["question"], method)
                        if existing_eval:
                            existing_eval["source_file"] = result["_source_file"]
                            new_evaluations.append(existing_eval)
                    else:
                        mix_eval = await self.evaluate_single_answer(
                            question=result["question"],
                            expected_answer=str(result["expected_answer"]),
                            generated_answer=str(result["mix_result"]["result"]),
                            evidence_pages=result.get("evidence_pages", ""),
                            evidence_sources=result.get("evidence_sources", ""),
                            doc_id=result["doc_id"],
                            evaluation_type=evaluation_type
                        )
                        mix_eval["method"] = method
                        mix_eval["source_file"] = result["_source_file"]
                        
                        new_evaluations.append(mix_eval)
                        
                        # 更新索引
                        key = (result["doc_id"], result["question"], method)
                        self.existing_evaluations[key] = mix_eval
                
                # 评估naive结果
                if result.get("naive_result") and result["naive_result"].get("success"):
                    method = "naive"
                    
                    # 检查是否已完成评估
                    if self.is_evaluation_completed(result["doc_id"], result["question"], method):
                        completed_count += 1
                        self.logger.info(f"  ✅ 跳过已完成的{method}评估")
                        # 将已有结果添加到当前批次
                        existing_eval = self.get_existing_evaluation(result["doc_id"], result["question"], method)
                        if existing_eval:
                            existing_eval["source_file"] = result["_source_file"]
                            new_evaluations.append(existing_eval)
                    else:
                        naive_eval = await self.evaluate_single_answer(
                            question=result["question"],
                            expected_answer=str(result["expected_answer"]),
                            generated_answer=str(result["naive_result"]["result"]),
                            evidence_pages=result.get("evidence_pages", ""),
                            evidence_sources=result.get("evidence_sources", ""),
                            doc_id=result["doc_id"],
                            evaluation_type=evaluation_type
                        )
                        naive_eval["method"] = method
                        naive_eval["source_file"] = result["_source_file"]
                        
                        new_evaluations.append(naive_eval)
                        
                        # 更新索引
                        key = (result["doc_id"], result["question"], method)
                        self.existing_evaluations[key] = naive_eval
            
            # 每10个结果保存一次
            if i % 10 == 0:
                # 更新evaluation_results并保存
                self.update_evaluation_results_list(new_evaluations)
                self.save_evaluation_results()
                self.logger.info(f"已保存前 {len(self.evaluation_results)} 个评估结果")
                new_evaluations = []  # 清空临时列表
        
        total_time = time.time() - start_time
        
        # 更新并保存最终结果
        if new_evaluations:
            self.update_evaluation_results_list(new_evaluations)
        self.save_evaluation_results()
        
        # 记录统计
        new_eval_count = len(self.evaluation_results) - len(self.existing_evaluations) + len(new_evaluations)
        if skipped_count > 0:
            self.logger.info(f"⏭️ 跳过了 {skipped_count} 个有错误的查询")
        if completed_count > 0:
            self.logger.info(f"✅ 跳过了 {completed_count} 个已完成的评估")
        self.logger.info(f"🆕 新完成了 {new_eval_count} 个评估")
        
        # 生成评估报告
        self.generate_evaluation_report(total_time)

    async def evaluate_vlm_results(self, vlm_results: List[Dict], evaluation_type: str):
        """评估VLM结果"""
        start_time = time.time()
        skipped_count = 0
        completed_count = 0
        new_evaluations = []
        
        # 统计已有评估
        if self.existing_evaluations:
            existing_count = len(self.existing_evaluations)
            self.logger.info(f"发现 {existing_count} 个已有的LLM评估结果，将跳过重复评估")
        
        for i, vlm_result in enumerate(vlm_results, 1):
            self.logger.info(f"\n📋 [{i}/{len(vlm_results)}] 评估VLM结果")
            
            # 检查是否有任何类型的error，如果有则跳过
            if self.has_any_error(vlm_result):
                skipped_count += 1
                self.logger.info(f"  ⏭️ 跳过有错误的VLM查询: {self.get_error_summary(vlm_result)}")
                continue
            
            # 评估VLM结果
            if vlm_result.get("vlm_result") and vlm_result["vlm_result"].get("success"):
                method = "vlm"
                
                # 检查是否已完成评估
                if self.is_evaluation_completed(vlm_result["doc_id"], vlm_result["question"], method):
                    completed_count += 1
                    self.logger.info(f"  ✅ 跳过已完成的{method}评估")
                    # 将已有结果添加到当前批次
                    existing_eval = self.get_existing_evaluation(vlm_result["doc_id"], vlm_result["question"], method)
                    if existing_eval:
                        new_evaluations.append(existing_eval)
                    continue
                
                vlm_eval = await self.evaluate_single_answer(
                    question=vlm_result["question"],
                    expected_answer=str(vlm_result["expected_answer"]),
                    generated_answer=str(vlm_result["vlm_result"]["result"]),
                    evidence_pages=vlm_result.get("evidence_pages", ""),
                    evidence_sources=vlm_result.get("evidence_sources", ""),
                    doc_id=vlm_result["doc_id"],
                    evaluation_type=evaluation_type
                )
                vlm_eval["method"] = method
                vlm_eval["model"] = vlm_result["vlm_result"].get("model", "unknown")
                
                new_evaluations.append(vlm_eval)
                
                # 更新索引
                key = (vlm_result["doc_id"], vlm_result["question"], method)
                self.existing_evaluations[key] = vlm_eval
            
            # 每10个结果保存一次
            if i % 10 == 0:
                # 更新evaluation_results并保存
                self.update_evaluation_results_list(new_evaluations)
                self.save_evaluation_results()
                self.logger.info(f"已保存前 {len(self.evaluation_results)} 个评估结果")
                new_evaluations = []  # 清空临时列表
        
        total_time = time.time() - start_time
        
        # 更新并保存最终结果
        if new_evaluations:
            self.update_evaluation_results_list(new_evaluations)
        self.save_evaluation_results()
        
        # 记录统计
        new_eval_count = len(new_evaluations) if new_evaluations else 0
        if skipped_count > 0:
            self.logger.info(f"⏭️ 跳过了 {skipped_count} 个有错误的VLM查询")
        if completed_count > 0:
            self.logger.info(f"✅ 跳过了 {completed_count} 个已完成的评估")
        self.logger.info(f"🆕 新完成了 {new_eval_count} 个评估")
        
        # 生成评估报告
        self.generate_evaluation_report(total_time)

    async def evaluate_standard_rag_results(self, rag_results: List[Dict], evaluation_type: str):
        """评估标准RAG结果（hybrid、mix和naive）"""
        start_time = time.time()
        skipped_count = 0
        completed_count = 0
        new_evaluations = []
        
        # 统计已有评估
        if self.existing_evaluations:
            existing_count = len(self.existing_evaluations)
            self.logger.info(f"发现 {existing_count} 个已有的LLM评估结果，将跳过重复评估")
        
        for i, rag_result in enumerate(rag_results, 1):
            self.logger.info(f"\n📋 [{i}/{len(rag_results)}] 评估RAG结果")
            
            # 检查是否有任何类型的error，如果有则跳过
            if self.has_any_error(rag_result):
                skipped_count += 1
                self.logger.info(f"  ⏭️ 跳过有错误的RAG查询: {self.get_error_summary(rag_result)}")
                continue
            
            # 评估hybrid结果
            if rag_result.get("hybrid_result") and rag_result["hybrid_result"].get("success"):
                method = "hybrid"
                
                # 检查是否已完成评估
                if self.is_evaluation_completed(rag_result["doc_id"], rag_result["question"], method):
                    completed_count += 1
                    self.logger.info(f"  ✅ 跳过已完成的{method}评估")
                    # 将已有结果添加到当前批次
                    existing_eval = self.get_existing_evaluation(rag_result["doc_id"], rag_result["question"], method)
                    if existing_eval:
                        new_evaluations.append(existing_eval)
                else:
                    hybrid_eval = await self.evaluate_single_answer(
                        question=rag_result["question"],
                        expected_answer=str(rag_result["expected_answer"]),
                        generated_answer=str(rag_result["hybrid_result"]["result"]),
                        evidence_pages=rag_result.get("evidence_pages", ""),
                        evidence_sources=rag_result.get("evidence_sources", ""),
                        doc_id=rag_result["doc_id"],
                        evaluation_type=evaluation_type
                    )
                    hybrid_eval["method"] = method
                    
                    new_evaluations.append(hybrid_eval)
                    
                    # 更新索引
                    key = (rag_result["doc_id"], rag_result["question"], method)
                    self.existing_evaluations[key] = hybrid_eval
            
            # 评估mix结果
            if rag_result.get("mix_result") and rag_result["mix_result"].get("success"):
                method = "mix"
                
                # 检查是否已完成评估
                if self.is_evaluation_completed(rag_result["doc_id"], rag_result["question"], method):
                    completed_count += 1
                    self.logger.info(f"  ✅ 跳过已完成的{method}评估")
                    # 将已有结果添加到当前批次
                    existing_eval = self.get_existing_evaluation(rag_result["doc_id"], rag_result["question"], method)
                    if existing_eval:
                        new_evaluations.append(existing_eval)
                else:
                    mix_eval = await self.evaluate_single_answer(
                        question=rag_result["question"],
                        expected_answer=str(rag_result["expected_answer"]),
                        generated_answer=str(rag_result["mix_result"]["result"]),
                        evidence_pages=rag_result.get("evidence_pages", ""),
                        evidence_sources=rag_result.get("evidence_sources", ""),
                        doc_id=rag_result["doc_id"],
                        evaluation_type=evaluation_type
                    )
                    mix_eval["method"] = method
                    
                    new_evaluations.append(mix_eval)
                    
                    # 更新索引
                    key = (rag_result["doc_id"], rag_result["question"], method)
                    self.existing_evaluations[key] = mix_eval
            
            # 评估naive结果
            if rag_result.get("naive_result") and rag_result["naive_result"].get("success"):
                method = "naive"
                
                # 检查是否已完成评估
                if self.is_evaluation_completed(rag_result["doc_id"], rag_result["question"], method):
                    completed_count += 1
                    self.logger.info(f"  ✅ 跳过已完成的{method}评估")
                    # 将已有结果添加到当前批次
                    existing_eval = self.get_existing_evaluation(rag_result["doc_id"], rag_result["question"], method)
                    if existing_eval:
                        new_evaluations.append(existing_eval)
                else:
                    naive_eval = await self.evaluate_single_answer(
                        question=rag_result["question"],
                        expected_answer=str(rag_result["expected_answer"]),
                        generated_answer=str(rag_result["naive_result"]["result"]),
                        evidence_pages=rag_result.get("evidence_pages", ""),
                        evidence_sources=rag_result.get("evidence_sources", ""),
                        doc_id=rag_result["doc_id"],
                        evaluation_type=evaluation_type
                    )
                    naive_eval["method"] = method
                    
                    new_evaluations.append(naive_eval)
                    
                    # 更新索引
                    key = (rag_result["doc_id"], rag_result["question"], method)
                    self.existing_evaluations[key] = naive_eval
            
            # 每10个结果保存一次
            if i % 10 == 0:
                # 更新evaluation_results并保存
                self.update_evaluation_results_list(new_evaluations)
                self.save_evaluation_results()
                self.logger.info(f"已保存前 {len(self.evaluation_results)} 个评估结果")
                new_evaluations = []  # 清空临时列表
        
        total_time = time.time() - start_time
        
        # 更新并保存最终结果
        if new_evaluations:
            self.update_evaluation_results_list(new_evaluations)
        self.save_evaluation_results()
        
        # 记录统计
        new_eval_count = len(new_evaluations) if new_evaluations else 0
        if skipped_count > 0:
            self.logger.info(f"⏭️ 跳过了 {skipped_count} 个有错误的RAG查询")
        if completed_count > 0:
            self.logger.info(f"✅ 跳过了 {completed_count} 个已完成的评估")
        self.logger.info(f"🆕 新完成了 {new_eval_count} 个评估")
        
        # 生成评估报告
        self.generate_evaluation_report(total_time)

    def save_evaluation_results(self):
        """保存评估结果"""
        # 保存详细的JSON结果
        results_file = os.path.join(self.config.output_dir, "llm_evaluation_results.json")
        with open(results_file, 'w', encoding='utf-8') as f:
            json.dump(self.evaluation_results, f, ensure_ascii=False, indent=2)
        
        # 保存CSV摘要
        summary_data = []
        for result in self.evaluation_results:
            summary_data.append({
                "doc_id": result["doc_id"],
                "method": result.get("method", ""),
                "source_file": result.get("source_file", ""),
                "question": result["question"][:100] + "..." if len(result["question"]) > 100 else result["question"],
                "expected_answer": str(result["expected_answer"])[:100] + "..." if len(str(result["expected_answer"])) > 100 else str(result["expected_answer"]),
                "generated_answer": str(result["generated_answer"])[:200] + "..." if len(str(result["generated_answer"])) > 200 else str(result["generated_answer"]),
                "accuracy": result.get("accuracy"),
                "relevance": result.get("relevance"),
                "completeness": result.get("completeness"),
                "faithfulness": result.get("faithfulness"),
                "clarity": result.get("clarity"),
                "consistency": result.get("consistency"),
                "overall_score": result.get("overall_score"),
                "evaluation_time": result.get("evaluation_time"),
                "success": result.get("success"),
                "error": result.get("error", "")
            })
        
        summary_file = os.path.join(self.config.output_dir, "llm_evaluation_summary.csv")
        df = pd.DataFrame(summary_data)
        df.to_csv(summary_file, index=False, encoding='utf-8')

    def generate_evaluation_report(self, total_time: float):
        """生成评估报告"""
        total_evaluations = len(self.evaluation_results)
        successful_evaluations = [r for r in self.evaluation_results if r.get("success")]
        
        if not successful_evaluations:
            self.logger.warning("没有成功的评估结果，无法生成报告")
            return
        
        # 按方法分组统计
        method_stats = {}
        source_file_stats = {}
        
        for result in successful_evaluations:
            method = result.get("method", "unknown")
            source_file = result.get("source_file", "unknown")
            
            # 方法统计
            if method not in method_stats:
                method_stats[method] = []
            method_stats[method].append(result)
            
            # 源文件统计
            if source_file not in source_file_stats:
                source_file_stats[source_file] = {}
            if method not in source_file_stats[source_file]:
                source_file_stats[source_file][method] = []
            source_file_stats[source_file][method].append(result)
        
        report = f"""
# LLM答案评估报告

## 总体统计
- 总评估数: {total_evaluations}
- 成功评估数: {len(successful_evaluations)}
- 失败评估数: {total_evaluations - len(successful_evaluations)}
- 总耗时: {total_time:.2f}秒
- 平均每评估耗时: {total_time/total_evaluations:.2f}秒

## 评估配置
- 评估模型: {getattr(self.config, 'model', 'gpt-4o')}
- 评估温度: 0.1
- 最大tokens: 1000

## 数据源统计
"""

        # 显示数据源信息
        for source_file, methods in source_file_stats.items():
            file_name = os.path.basename(source_file)
            total_from_source = sum(len(results) for results in methods.values())
            report += f"- {file_name}: {total_from_source} 个评估 ({', '.join(methods.keys())})\n"

        # 为每种方法生成统计
        for method, results in method_stats.items():
            accuracy_scores = [r.get("accuracy") for r in results if r.get("accuracy") is not None]
            
            report += f"""
## {method.upper()}方法评估结果

### 准确性统计
- 评估样本数: {len(results)}
- 准确答案数: {sum(accuracy_scores)}
- 准确率: {(sum(accuracy_scores) / len(accuracy_scores) * 100):.1f}%

"""
            
            # 如果有其他指标，也包含在报告中
            if any(r.get("relevance") is not None for r in results):
                relevance_scores = [r.get("relevance") for r in results if r.get("relevance") is not None]
                completeness_scores = [r.get("completeness") for r in results if r.get("completeness") is not None]
                faithfulness_scores = [r.get("faithfulness") for r in results if r.get("faithfulness") is not None]
                clarity_scores = [r.get("clarity") for r in results if r.get("clarity") is not None]
                consistency_scores = [r.get("consistency") for r in results if r.get("consistency") is not None]
                overall_scores = [r.get("overall_score") for r in results if r.get("overall_score") is not None]
                
                if relevance_scores:
                    report += f"""### 多维度评估统计
- 相关性平均分: {(sum(relevance_scores) / len(relevance_scores)):.3f}
- 完整性平均分: {(sum(completeness_scores) / len(completeness_scores)):.3f}
- 忠实性平均分: {(sum(faithfulness_scores) / len(faithfulness_scores)):.3f}
- 清晰度平均分: {(sum(clarity_scores) / len(clarity_scores)):.3f}
- 一致性平均分: {(sum(consistency_scores) / len(consistency_scores)):.3f}
- 总体评分平均: {(sum(overall_scores) / len(overall_scores)):.3f}

"""

        # 方法对比
        if len(method_stats) > 1:
            report += """
## 方法对比

| 方法 | 样本数 | 准确率 | 平均总体评分 |
|------|--------|--------|--------------|
"""
            for method, results in method_stats.items():
                accuracy_scores = [r.get("accuracy") for r in results if r.get("accuracy") is not None]
                overall_scores = [r.get("overall_score") for r in results if r.get("overall_score") is not None]
                
                accuracy_rate = (sum(accuracy_scores) / len(accuracy_scores) * 100) if accuracy_scores else 0
                avg_overall = (sum(overall_scores) / len(overall_scores)) if overall_scores else 0
                
                report += f"| {method} | {len(results)} | {accuracy_rate:.1f}% | {avg_overall:.3f} |\n"

        # 按文档分析（显示所有文档，不只是多方法的）
        doc_comparison = {}
        for result in successful_evaluations:
            doc_id = result["doc_id"]
            method = result.get("method", "unknown")
            
            if doc_id not in doc_comparison:
                doc_comparison[doc_id] = {}
            if method not in doc_comparison[doc_id]:
                doc_comparison[doc_id][method] = []
            doc_comparison[doc_id][method].append(result)

        # 显示所有文档的分析（不论方法数量）
        if doc_comparison:
            # 找到被多种方法处理的文档
            multi_method_docs = {doc_id: methods for doc_id, methods in doc_comparison.items() if len(methods) > 1}
            single_method_docs = {doc_id: methods for doc_id, methods in doc_comparison.items() if len(methods) == 1}
            
            if multi_method_docs:
                report += f"""
## 相同文档的方法对比

共有 {len(multi_method_docs)} 个文档被多种方法处理：

| 文档ID | 方法 | 准确答案数/总问题数 | 准确率 |
|--------|------|-------------------|--------|
"""
                for doc_id, methods in multi_method_docs.items():
                    for method, results in methods.items():
                        accuracy_scores = [r.get("accuracy") for r in results if r.get("accuracy") is not None]
                        accuracy_count = sum(accuracy_scores)
                        total_count = len(accuracy_scores)
                        accuracy_rate = (accuracy_count / total_count * 100) if total_count > 0 else 0
                        
                        short_doc_id = doc_id[:30] + "..." if len(doc_id) > 30 else doc_id
                        report += f"| {short_doc_id} | {method} | {accuracy_count}/{total_count} | {accuracy_rate:.1f}% |\n"
            
            if single_method_docs:
                # 选择显示的方法（优先VLM，然后是其他方法）
                available_methods = list(method_stats.keys())
                primary_method = "vlm" if "vlm" in available_methods else available_methods[0]
                
                report += f"""
## 文档级别评估结果 ({primary_method.upper()}方法)

按文档分析准确率表现：

| 文档ID | 准确答案数/总问题数 | 准确率 | 文档类型 |
|--------|-------------------|--------|----------|
"""
                # 按准确率排序显示文档
                doc_performance = []
                for doc_id, methods in single_method_docs.items():
                    if primary_method in methods:
                        results = methods[primary_method]
                        accuracy_scores = [r.get("accuracy") for r in results if r.get("accuracy") is not None]
                        accuracy_count = sum(accuracy_scores)
                        total_count = len(accuracy_scores)
                        accuracy_rate = (accuracy_count / total_count * 100) if total_count > 0 else 0
                        
                        # 获取文档类型信息
                        doc_types = set()
                        for r in results:
                            evidence_sources = r.get("evidence_sources", "")
                            if "arxiv" in evidence_sources.lower():
                                doc_types.add("学术论文")
                            elif "10k" in doc_id.lower():
                                doc_types.add("财报")
                            elif any(keyword in doc_id.lower() for keyword in ["manual", "guide", "handbook"]):
                                doc_types.add("手册指南")
                            elif any(keyword in doc_id.lower() for keyword in ["report", "survey"]):
                                doc_types.add("调研报告")
                            else:
                                doc_types.add("其他")
                        
                        doc_type = ", ".join(doc_types) if doc_types else "未知"
                        
                        doc_performance.append({
                            "doc_id": doc_id,
                            "accuracy_count": accuracy_count,
                            "total_count": total_count,
                            "accuracy_rate": accuracy_rate,
                            "doc_type": doc_type
                        })
                
                # 按准确率降序排序
                doc_performance.sort(key=lambda x: x["accuracy_rate"], reverse=True)
                
                # 显示前30个文档（避免报告过长）
                display_docs = doc_performance[:30]
                for doc_info in display_docs:
                    short_doc_id = doc_info["doc_id"][:30] + "..." if len(doc_info["doc_id"]) > 30 else doc_info["doc_id"]
                    report += f"| {short_doc_id} | {doc_info['accuracy_count']}/{doc_info['total_count']} | {doc_info['accuracy_rate']:.1f}% | {doc_info['doc_type']} |\n"
                
                if len(doc_performance) > 30:
                    report += f"\n注：仅显示前30个文档，总共有{len(doc_performance)}个文档被评估。\n"
                
                # 按文档类型统计
                type_stats = {}
                for doc_info in doc_performance:
                    doc_type = doc_info["doc_type"]
                    if doc_type not in type_stats:
                        type_stats[doc_type] = {"count": 0, "total_questions": 0, "correct_answers": 0}
                    type_stats[doc_type]["count"] += 1
                    type_stats[doc_type]["total_questions"] += doc_info["total_count"]
                    type_stats[doc_type]["correct_answers"] += doc_info["accuracy_count"]
                
                report += f"""
### 按文档类型统计

| 文档类型 | 文档数量 | 总问题数 | 正确答案数 | 准确率 |
|----------|----------|----------|------------|--------|
"""
                for doc_type, stats in type_stats.items():
                    accuracy_rate = (stats["correct_answers"] / stats["total_questions"] * 100) if stats["total_questions"] > 0 else 0
                    report += f"| {doc_type} | {stats['count']} | {stats['total_questions']} | {stats['correct_answers']} | {accuracy_rate:.1f}% |\n"

        report += f"""

## 输出文件
- 详细评估结果: {os.path.join(self.config.output_dir, 'llm_evaluation_results.json')}
- 评估结果摘要: {os.path.join(self.config.output_dir, 'llm_evaluation_summary.csv')}
- 评估日志: {os.path.join(self.config.output_dir, 'llm_evaluation.log')}
"""

        # 保存报告
        report_file = os.path.join(self.config.output_dir, "llm_evaluation_report.md")
        with open(report_file, 'w', encoding='utf-8') as f:
            f.write(report)
        
        self.logger.info("\n" + "="*50)
        self.logger.info("LLM评估完成!")
        self.logger.info(f"详细结果: {os.path.join(self.config.output_dir, 'llm_evaluation_results.json')}")
        self.logger.info(f"结果摘要: {os.path.join(self.config.output_dir, 'llm_evaluation_summary.csv')}")
        self.logger.info(f"评估报告: {report_file}")
        self.logger.info("="*50)

    def has_any_error(self, result: Dict[str, Any]) -> bool:
        """检查结果是否有任何类型的错误"""
        # 检查顶层error
        if result.get("error"):
            return True
        
        # 检查VLM结果的error
        vlm_result = result.get("vlm_result")
        if vlm_result and (vlm_result.get("error") or not vlm_result.get("success", True)):
            return True
        
        # 检查RAG hybrid结果的error
        hybrid_result = result.get("hybrid_result")
        if hybrid_result and (hybrid_result.get("error") or not hybrid_result.get("success", True)):
            return True
        
        # 检查RAG mix结果的error
        mix_result = result.get("mix_result")
        if mix_result and (mix_result.get("error") or not mix_result.get("success", True)):
            return True
        
        # 检查RAG naive结果的error
        naive_result = result.get("naive_result")
        if naive_result and (naive_result.get("error") or not naive_result.get("success", True)):
            return True
        
        return False
    
    def get_error_summary(self, result: Dict[str, Any]) -> str:
        """获取错误摘要信息"""
        errors = []
        
        # 顶层error
        if result.get("error"):
            error_msg = result["error"]
            if "无法找到文档" in error_msg:
                errors.append("文档不存在")
            else:
                errors.append(f"顶层错误: {error_msg[:50]}...")
        
        # VLM错误
        vlm_result = result.get("vlm_result")
        if vlm_result and (vlm_result.get("error") or not vlm_result.get("success", True)):
            error_msg = vlm_result.get("error", "VLM查询失败")
            if "context_length_exceeded" in error_msg:
                errors.append("VLM-Token超限")
            else:
                errors.append(f"VLM错误: {error_msg[:50]}...")
        
        # RAG错误
        hybrid_result = result.get("hybrid_result")
        if hybrid_result and (hybrid_result.get("error") or not hybrid_result.get("success", True)):
            error_msg = hybrid_result.get("error", "Hybrid查询失败")
            errors.append(f"Hybrid错误: {error_msg[:50]}...")
        
        mix_result = result.get("mix_result")
        if mix_result and (mix_result.get("error") or not mix_result.get("success", True)):
            error_msg = mix_result.get("error", "Mix查询失败")
            errors.append(f"Mix错误: {error_msg[:50]}...")
        
        naive_result = result.get("naive_result")
        if naive_result and (naive_result.get("error") or not naive_result.get("success", True)):
            error_msg = naive_result.get("error", "Naive查询失败")
            errors.append(f"Naive错误: {error_msg[:50]}...")
        
        return "; ".join(errors) if errors else "未知错误"

    def load_existing_evaluations(self):
        """加载已有的评估结果"""
        results_file = os.path.join(self.config.output_dir, "llm_evaluation_results.json")
        
        if os.path.exists(results_file):
            try:
                with open(results_file, 'r', encoding='utf-8') as f:
                    existing_data = json.load(f)
                
                self.evaluation_results = existing_data
                self.logger.info(f"加载了 {len(existing_data)} 个已有的LLM评估结果")
                
                # 构建快速查找索引：{(doc_id, question, method): result}
                for result in existing_data:
                    key = (result["doc_id"], result["question"], result.get("method", ""))
                    self.existing_evaluations[key] = result
                
                self.logger.info(f"构建了 {len(self.existing_evaluations)} 个LLM评估结果的查找索引")
                
            except Exception as e:
                self.logger.warning(f"加载已有LLM评估结果时出错：{e}，将从头开始评估")
                self.evaluation_results = []
                self.existing_evaluations = {}
        else:
            self.logger.info("未找到已有LLM评估结果文件，将从头开始评估")

    def is_evaluation_completed(self, doc_id: str, question: str, method: str) -> bool:
        """检查指定的评估是否已完成"""
        key = (doc_id, question, method)
        if key in self.existing_evaluations:
            result = self.existing_evaluations[key]
            # 检查评估是否成功完成
            if result.get("success") is True and result.get("accuracy") is not None:
                return True
        return False

    def get_existing_evaluation(self, doc_id: str, question: str, method: str):
        """获取已存在的评估结果"""
        key = (doc_id, question, method)
        return self.existing_evaluations.get(key)

    def update_evaluation_results_list(self, new_results: List[Dict[str, Any]]):
        """更新评估结果列表，移除旧的结果并添加新的结果"""
        # 为了避免重复，先移除已存在的相同评估
        existing_keys = set()
        for result in new_results:
            key = (result["doc_id"], result["question"], result.get("method", ""))
            existing_keys.add(key)
        
        # 移除旧的重复结果
        self.evaluation_results = [
            r for r in self.evaluation_results 
            if (r["doc_id"], r["question"], r.get("method", "")) not in existing_keys
        ]
        
        # 添加新结果
        self.evaluation_results.extend(new_results)
        
        self.logger.debug(f"更新LLM评估结果，当前总结果数: {len(self.evaluation_results)}")

class EvaluationConfig:
    def __init__(self, args):
        # 支持多个结果文件
        if hasattr(args, 'rag_results_files') and args.rag_results_files:
            self.rag_results_files = args.rag_results_files
            self.rag_results_file = None  # 兼容性
        else:
            self.rag_results_file = args.rag_results_file
            self.rag_results_files = [args.rag_results_file] if args.rag_results_file else []
        
        self.output_dir = args.output_dir
        self.api_key = args.api_key
        self.base_url = args.base_url
        self.evaluation_type = args.evaluation_type
        self.max_evaluations = args.max_evaluations

def main():
    import argparse
    
    parser = argparse.ArgumentParser(description="LLM答案评估器")
    
    # 支持多个文件输入
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--rag-results-file", "-r",
        help="单个RAG评估结果文件路径（JSON格式）"
    )
    group.add_argument(
        "--rag-results-files", "-rf", 
        nargs="+",
        help="多个结果文件路径（支持RAG和VLM混合，JSON格式）"
    )
    
    parser.add_argument(
        "--output-dir", "-o",
        default="./evaluation_results",
        help="评估结果输出目录（默认：./llm_evaluation_results）"
    )
    parser.add_argument(
        "--api-key",
        default=os.getenv("LLM_BINDING_API_KEY"),
        help="OpenAI API密钥（默认从环境变量LLM_BINDING_API_KEY读取）",
    )
    parser.add_argument(
        "--base-url",
        default=os.getenv("LLM_BINDING_HOST"),
        help="API基础URL（可选）",
    )
    parser.add_argument(
        "--evaluation-type", "-t",
        choices=["accuracy_only", "comprehensive"],
        default="comprehensive",
        help="评估类型：仅准确性或综合评估（默认：comprehensive）"
    )
    parser.add_argument(
        "--max-evaluations", "-m",
        type=int,
        help="最大评估数量（用于测试，留空则评估所有结果）"
    )

    args = parser.parse_args()

    # 检查API密钥
    if not args.api_key:
        print("错误：需要OpenAI API密钥")
        print("请设置环境变量LLM_BINDING_API_KEY或使用--api-key选项")
        return

    # 检查结果文件
    files_to_check = []
    if args.rag_results_file:
        files_to_check = [args.rag_results_file]
    elif args.rag_results_files:
        files_to_check = args.rag_results_files

    for file_path in files_to_check:
        if not os.path.exists(file_path):
            print(f"错误：结果文件不存在：{file_path}")
            return

    # 创建配置
    config = EvaluationConfig(args)
    
    # 创建评估器
    evaluator = LLMAnswerEvaluator(config)
    
    # 开始评估
    print("LLM答案评估器")
    print("=" * 50)
    
    if config.rag_results_file:
        print(f"结果文件：{config.rag_results_file}")
    else:
        print(f"结果文件：{config.rag_results_files}")
        
    print(f"输出目录：{config.output_dir}")
    print(f"评估类型：{config.evaluation_type}")
    if config.max_evaluations:
        print(f"最大评估数：{config.max_evaluations}")
    print("=" * 50)
    print("\n开始评估...")
    
    # 运行评估
    try:
        if len(config.rag_results_files) > 1:
            # 多文件评估
            asyncio.run(evaluator.evaluate_multiple_results(
                config.rag_results_files, 
                config.evaluation_type,
                config.max_evaluations
            ))
        else:
            # 单文件评估（兼容性）
            asyncio.run(evaluator.evaluate_rag_results(
                config.rag_results_files[0], 
                config.evaluation_type,
                config.max_evaluations
            ))
    except KeyboardInterrupt:
        print("\n用户中断，程序退出")
    except Exception as e:
        print(f"\n评估过程中发生错误：{e}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    main() 